# This worflow will call the GitHub API to download the previous day audit log and commit/push the new file to this repo.

name: Log Capture

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule daily at 8am
  schedule:
  - cron: '0 8 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "get_audit_logs"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Test the API using TOKEN and fail immediately if not http 200
      - name: Test the TOKEN and API
        run: |
          if [ $(curl --silent -H "Authorization: token ${{ secrets.PAT_TOKEN }}" "https://api.github.com/orgs/${{ secrets.ORG_NAME }}/audit-log" --write-out "%{http_code}" --output /dev/null) -ne 200 ]; then echo "HTTP Response NOT 200, Check CURL and TOKEN"; exit 1; else echo "HTTP Response 200 received assumed PAT and CURL are good"; fi

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Define yesterday
      - name: Define yesterday
        id: yesterday
        run: echo "yesterdaynew=$(date --date='yesterday' +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      # Curl the audit log filtered to yesterday to a dated filename
      - name: Get the audit log
        run: 'curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.PAT_TOKEN }}" "https://api.github.com/orgs/${{ secrets.ORG_NAME }}/audit-log?include=all&phrase=created:${{ steps.yesterday.outputs.yesterday }}" > audit-${{ steps.yesterday.outputs.yesterday }}.log'

      # Add, commit, then push the new file to the repo
      - name: Adds the new log file to the repo
        run: git add .
      - name: Commit change to repo
        run: git -c user.email="${{ secrets.EMAIL }}" -c user.name="${{ secrets.USERNAME }}" commit -am "Adding logs for ${{ steps.yesterday.outputs.yesterday }}"
      - name: Push change to repo
        run: git push origin main
